wandb_version: 1

^BRANCH_LENGTH:
  desc: null
  value: '0.1111111111111111'
^BRANCH_THICCNESS:
  desc: null
  value: '0.015'
^FIRST_BRANCH_HEIGHT:
  desc: null
  value: '0.24'
^LIGHT_DIF:
  desc: null
  value: '250'
^LIGHT_WIDTH:
  desc: null
  value: '0.25'
^MAX_BRANCHING:
  desc: null
  value: '10'
^algo:
  desc: null
  value: ppo
^alpha:
  desc: null
  value: '0.99'
^clip_param:
  desc: null
  value: '0.1'
^cuda_deterministic:
  desc: null
  value: 'False'
^custom_gym:
  desc: null
  value: growspace
^entropy_coef:
  desc: null
  value: '0.01'
^eps:
  desc: null
  value: 1e-05
^gae_lambda:
  desc: null
  value: '0.95'
^gail:
  desc: null
  value: 'False'
^gail_batch_size:
  desc: null
  value: '128'
^gail_epoch:
  desc: null
  value: '5'
^gail_experts_dir:
  desc: null
  value: ./gail_experts
^gamma:
  desc: null
  value: '0.99'
^lr:
  desc: null
  value: '0.00025'
^max_grad_norm:
  desc: null
  value: '0.5'
^num_mini_batch:
  desc: null
  value: '32'
^num_processes:
  desc: null
  value: '1'
^num_steps:
  desc: null
  value: '2500'
^ppo_epoch:
  desc: null
  value: '4'
^seed:
  desc: null
  value: '1'
^use_gae:
  desc: null
  value: 'True'
^value_loss_coef:
  desc: null
  value: '0.5'
_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 3
      4: 3.8.5
      5: 0.10.23
      8:
      - 5
